name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: '0.1.0'
        required: true

jobs:
  publish:
    name: Publish library at mavenCentral
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prebuild library
        run: ./gradlew publishToMavenLocal
  release:
    name: Create release
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: ${{ github.ref }}
          tag_name: release/${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          body: "Will be filled later"
          draft: true
